// Migrazione UNA TANTUM: importa i vini rossi che finora vivevano in
// frontend/src/data/data.js (VINI_ROSSI) nel database, prima che
// l'array venga rimosso e la categoria "rossi" passi a leggere dalla
// stessa API che questo script popola.
// NOTA: i due campi `img` originali (bundle Vite) non sono migrati —
// sono riferimenti a asset del frontend, non URL utilizzabili dal DB;
// andranno ricaricati altrove quando ci sarà un hosting immagini reale.
// Uso: node scripts/importRossi.js
require("dotenv").config();
const mongoose = require("mongoose");
const Wine = require("../models/Wine");

const ROSSI = [
  { name: "Montepulciano d'Abruzzo Marina Cvetic Masciarelli", regione: "Abruzzo", colore: "Rosso", anno: "2012", description: "Vino rosso strutturato, affinato in legno, con note di frutta scura matura, spezie e tannini morbidi ma decisi — ottimo con carni rosse e piatti abruzzesi robusti." },
  { name: "Montepulciano d'Abruzzo Villa Gemma Masciarelli", regione: "Abruzzo", colore: "Rosso", anno: "2012", description: "Vino rosso elegante, con profumi di frutti rossi e note floreali, tannini setosi e finale persistente — ideale con arrosti e formaggi stagionati." },
  { name: "Blauburgunder Mazzon Gottardi", regione: "Alto Adige", description: "Pinot Nero dalla storica collina di Mazzon: ciliegia, sottobosco e sorso fine e teso — elegante con salumi e piatti di funghi." },
  { name: "Blauburgunder Falkenstein", regione: "Alto Adige", description: "Pinot Nero in stile altoatesino, fragrante di piccoli frutti rossi, con freschezza alpina e tannino delicato — versatile a tutto pasto." },
  { name: "Lago di Caldaro San Michele Appiano", regione: "Alto Adige", description: "Rosso leggero e beverino da uva Schiava: fragolina, mandorla e sorso morbido — perfetto servito fresco con taglieri e cucina di montagna." },
  { name: "Lagrein Cantina Termeno", regione: "Alto Adige", description: "Rosso scuro e vellutato, con frutti neri, viola e una nota di cacao — abbinamento naturale con carni alla griglia e speck." },
  { name: "Lagrein Carlotto", regione: "Alto Adige", description: "Lagrein intenso dal frutto croccante, morbido al palato con finale leggermente ammandorlato — ottimo con arrosti e formaggi di malga." },
  { name: "Lagrein San Michele Appiano", regione: "Alto Adige", description: "Interpretazione elegante del Lagrein: mora, prugna e cacao su tannini fitti ma gentili — da carni rosse e cucina tirolese." },
  { name: "Merlot Sanct Valentin San Michele Appiano", regione: "Alto Adige", description: "Merlot della linea Sanct Valentin: ricco, avvolgente, con frutto maturo e legno dolce — al meglio con brasati e formaggi stagionati." },
  { name: "Pinot Nero Cantina Termeno", regione: "Alto Adige", description: "Pinot Nero fragrante e succoso, tra ciliegia e spezie dolci, dal sorso agile — compagno ideale di primi saporiti e carni bianche." },
  { name: "Pinot Nero Carlotto", regione: "Alto Adige", description: "Pinot Nero artigianale dal profilo fine: piccoli frutti rossi, freschezza e beva scorrevole — ottimo anche leggermente fresco." },
  { name: "Pinot Nero San Michele Appiano", regione: "Alto Adige", description: "Un classico dell'Alto Adige: ciliegia, lampone e note terrose, con eleganza e freschezza — versatile dalla pasta al pollame." },
  { name: "Pinot Nero Hofstatter", regione: "Alto Adige", description: "Firma storica del Pinot Nero altoatesino: profumato, setoso, di grande equilibrio — perfetto con carni bianche e funghi porcini." },
  { name: "Pinot Nero Nals Margreid", regione: "Alto Adige", description: "Pinot Nero di montagna, fragrante e minerale, con tannino sottile — da provare con piatti autunnali e salmerino affumicato." },
  { name: "Pinot Nero Abbazia di Novacella", regione: "Alto Adige", description: "Dai vigneti più a nord d'Italia, un Pinot Nero fresco e speziato dalla beva slanciata — ideale con canederli e salumi." },
  { name: "Pinot Nero Maso Cantaghel", regione: "Alto Adige", description: "Pinot Nero di piccolo maso: frutto rosso croccante, note di sottobosco e sorso fine — per chi cerca autenticità di montagna." },
  { name: "Pinot nero Krafuss Lageder", regione: "Alto Adige", description: "Cru di Pinot Nero coltivato in biodinamica: elegante, profondo, con frutto puro e spezie — da carni delicate e piatti ai funghi." },
  { name: "Pinot Nero Riserva Hofstatter", regione: "Alto Adige", description: "Riserva di grande stoffa: frutto maturo, spezie e legno ben dosato, tannino di seta — da stappare con arrosti importanti." },
  { name: "Pinot Nero Riserva San Michele Appiano", regione: "Alto Adige", description: "Affinamento paziente per un Pinot Nero profondo ed elegante, tra amarena, spezie e sottobosco — per le occasioni che contano." },
  { name: "Pinot Nero Sanct Valentin San Michele Appiano", regione: "Alto Adige", description: "Il vertice del Pinot Nero di San Michele Appiano: complesso, setoso, di lunga persistenza — grande vino da selvaggina e meditazione." },
  { name: "Pinot nero Vigna Sant'Urbano Hofstatter", regione: "Alto Adige", description: "Leggendario cru di Mazzon: profondità quasi borgognona, frutto nobile e spezie fini — uno dei grandi Pinot Nero italiani." },
  { name: "Santa Maddalena San Michele Appiano", regione: "Alto Adige", description: "Il rosso quotidiano di Bolzano: Schiava succosa con viola e mandorla, beva irresistibile — perfetto con speck e canederli." },
  { name: "Santa Maddalena Abbazia di Novacella", regione: "Alto Adige", description: "Santa Maddalena fragrante e gentile, tra frutti rossi e mandorla dolce — un classico altoatesino da tutto pasto." },
  { name: "Schiava Hofstatter", regione: "Alto Adige", description: "Schiava tipica: leggera, profumata di fragola e viola, deliziosa servita fresca — da aperitivi e taglieri." },
  { name: "Schiava Nals Margreid", regione: "Alto Adige", description: "La beva facile della tradizione altoatesina: frutto rosso croccante e sorso snello — ottima con pizza e cucina informale." },
  { name: "Taurasi Terredora", regione: "Campania", description: "Aglianico d'Irpinia austero e profondo: amarena, tabacco e spezie su tannino importante — da grandi arrosti e lunghi invecchiamenti." },
  { name: "Taurasi Radici Mastroberardino", regione: "Campania", description: "Il Taurasi per antonomasia: struttura, frutta scura, cuoio e liquirizia — un patriarca del Sud da carni importanti." },
  { name: "Gutturnio Costa dei Salina Perinelli", regione: "Emilia Romagna", description: "Gutturnio fermo dei colli piacentini, Barbera e Croatina: frutto pieno e sorso caldo — con i salumi piacentini è di casa." },
  { name: "Gutturnio Vivace Perinelli", regione: "Emilia Romagna", description: "La versione vivace del Gutturnio: brioso, fruttato, di beva golosa — nato per coppa, salame e tortelli." },
  { name: "Lambrusco dell'Emilia Nivolae Chiarli", regione: "Emilia Romagna", description: "Lambrusco dalla spuma vivace e dal frutto fragrante — l'allegria della tavola emiliana, perfetto con salumi e gnocco fritto." },
  { name: "Lambrusco Vigna Cà del Fiore Manicardi", regione: "Emilia Romagna", description: "Lambrusco di vigna singola: profumi di ciliegia e viola, spuma fine e sorso asciutto — da provare con tigelle e parmigiano." },
  { name: "Marzieno Fattoria Zerbina", regione: "Emilia Romagna", description: "Rosso di Romagna di carattere, Sangiovese con uve internazionali: frutto scuro, spezie e struttura — da carni alla brace." },
  { name: "Cabernet Franc Russiz Superiore", regione: "Friuli", description: "Cabernet Franc del Collio: elegante nota erbacea, piccoli frutti neri e sorso saporito — con le carni alla griglia dà il meglio." },
  { name: "Cabernet Sauvignon Marco Felluga", regione: "Friuli", description: "Cabernet Sauvignon friulano dal frutto netto e dai tannini levigati — versatile con secondi di carne e formaggi di media stagionatura." },
  { name: "Cabernet Sauvignon Crearo Pradio", regione: "Friuli", description: "Cabernet dal carattere morbido e speziato, con frutto maturo e legno discreto — piacevole da subito con le grigliate." },
  { name: "Merlot Russiz Superiore", regione: "Friuli", description: "Merlot di collina: prugna, ciliegia e velluto al palato, finale lungo — un classico friulano da carni e formaggi." },
  { name: "Merlot Roncomoro Pradio", regione: "Friuli", description: "Merlot succoso e diretto, dal frutto polposo e beva morbida — accompagna con disinvoltura la cucina di ogni giorno." },
  { name: "Pignacolusse Jermann", regione: "Friuli", description: "Rarità da uva Pignolo firmata Jermann: rosso profondo, speziato, di grande materia — bottiglia da intenditori con i brasati." },
  { name: "Pinot Nero Jermann", regione: "Friuli", description: "Pinot Nero secondo Jermann: eleganza, frutto fine e freschezza — perfetto con anatra e piatti di funghi." },
  { name: "Refosco Pradio", regione: "Friuli", description: "Refosco dal peduncolo rosso: frutti di bosco, vena acida vivace e finale ammandorlato — il rosso identitario del Friuli." },
  { name: "Refosco Dario Cos", regione: "Friuli", description: "Refosco artigianale, ruvido il giusto e ricco di frutti selvatici — chiama salumi friulani e piatti robusti." },
  { name: "Refosco Vigna Petrussa", regione: "Friuli", description: "Refosco di vigna dal frutto scuro e profondo, tannino vivo e bella freschezza — da provare con la selvaggina da penna." },
  { name: "Rosso Riserva degli Orzoni Russiz Superiore", regione: "Friuli", description: "Riserva di taglio bordolese del Collio: complessa, elegante, con frutto maturo e spezie — per le cene importanti." },
  { name: "Schioppettino Vigna Petrussa", regione: "Friuli", description: "Schioppettino di Prepotto: pepe nero, frutti di bosco e sorso slanciato — un autoctono raffinato da riscoprire." },
  { name: "Barbera Oltrepò Pavese Quaquarini", regione: "Lombardia", description: "Barbera dell'Oltrepò genuina e succosa, dal frutto vivo e acidità golosa — con risotti e salumi non tradisce mai." },
  { name: "Bonarda Oltrepò Pavese Quaquarini", regione: "Lombardia", description: "Bonarda vivace da uva Croatina: frutto scuro, morbidezza e spuma allegra — la regina della tavola oltrepadana." },
  { name: "Bonarda Oltrepò Pavese Giorgi", regione: "Lombardia", description: "Bonarda dal sorso pieno e vellutato, profumata di prugna e viola — perfetta con salame di Varzi e primi al ragù." },
  { name: "Bonarda Oltrepò Pavese Albani", regione: "Lombardia", description: "Interpretazione classica della Bonarda: fruttata, avvolgente, di beva immediata — da condividere con taglieri generosi." },
  { name: "Buttafuoco Oltrepò Pavese Quaquarini", regione: "Lombardia", description: "Il rosso fiero dell'Oltrepò: strutturato, caldo, dal frutto intenso — nato per brasati e formaggi saporiti." },
  { name: "Curtefranca Rosso Cà del Bosco", regione: "Lombardia", description: "Taglio bordolese di Franciacorta: frutto elegante, spezie e tannino fine — una firma prestigiosa anche fuori dalle bollicine." },
  { name: "Curtefranca Rosso Cavalleri", regione: "Lombardia", description: "Rosso franciacortino armonioso, tra frutti rossi e gentili note erbacee — piacevole con carni bianche e paste ripiene." },
  { name: "Grumello Sassorosso Nino Negri", regione: "Lombardia", description: "Nebbiolo di Valtellina dal cru Grumello: profumi alpini, tannino elegante e sapidità di montagna — con pizzoccheri e bresaola." },
  { name: "Inferno Nino Negri", regione: "Lombardia", description: "Dal vigneto più impervio della Valtellina: Nebbiolo teso, minerale, dal frutto asciutto — un rosso di roccia e carattere." },
  { name: "Roverone Nettare dei Santi", regione: "Lombardia", description: "Rosso importante delle colline di San Colombano, morbido e maturo — l'orgoglio della produzione locale con gli arrosti." },
  { name: "San Colombano DOC Nettare dei Santi", regione: "Lombardia", description: "La DOC di casa nostra: rosso fruttato e schietto delle colline di San Colombano — chilometro zero da bere con i salumi nostrani." },
  { name: "San Rocco Secco Nettare dei Santi", regione: "Lombardia", description: "Rosso fermo e asciutto della tradizione di San Colombano, dal frutto franco — quotidiano, sincero, a chilometro zero." },
  { name: "Sangue di Giuda Oltrepò Pavese Quaquarini", regione: "Lombardia", description: "Dolce e vivace, dal frutto rosso goloso: il rosso amabile dell'Oltrepò — da provare con crostate e pasticceria secca." },
  { name: "Sforzato di Valtellina 5 stelle Nino Negri", regione: "Lombardia", description: "Lo Sforzato simbolo della Valtellina: uve appassite, potenza vellutata e note di frutta sotto spirito — grande vino da meditazione." },
  { name: "Sforzato di Valtellina Canua Conti Sertoli Salis", regione: "Lombardia", description: "Sforzato profondo e caldo, tra prugna secca, spezie e cacao — da abbinare a brasati e formaggi d'alpeggio stagionati." },
  { name: "Tajardino Cavalleri", regione: "Lombardia", description: "Rosso franciacortino di carattere, frutto maturo e trama fitta ma elegante — con carni rosse e cacciagione gentile." },
  { name: "Valtellina Superiore Corte Meridiana Conti Sertoli Salis", regione: "Lombardia", description: "Nebbiolo delle Alpi elegante e sapido, dal tannino sottile — la montagna nel bicchiere, ideale con bresaola e formaggi di grotta." },
  { name: "Valtellina Superiore Mazer Nino Negri", regione: "Lombardia", description: "Valtellina Superiore di stoffa: rosa appassita, frutti rossi e mineralità — accompagna casseruole e piatti valtellinesi." },
  { name: "Montepulciano d'Abruzzo Jorio Umani Ronchi", regione: "Marche", description: "Montepulciano generoso e succoso: mora, ciliegia e spezie dolci su tannino morbido — un rapporto qualità prezzo da applausi." },
  { name: "Pelago Umani Ronchi", regione: "Marche", description: "Blend di Montepulciano e uve bordolesi: profondo, moderno, vellutato — bottiglia importante per carni rosse e occasioni speciali." },
  { name: "Aglianico del Molise Contaldo Di Majo Norante", regione: "Molise", description: "Aglianico molisano caldo e speziato, dal frutto scuro e tannino deciso — con agnello e cucina rustica del Sud." },
  { name: "Albarossa Montald Michele Chiarlo", regione: "Piemonte", description: "Da un incrocio tra Nebbiolo e Barbera: colore fitto, frutto ricco e freschezza — un piemontese moderno e avvolgente." },
  { name: "Barbaresco Produttori del Barbaresco", regione: "Piemonte", description: "Dalla cooperativa più celebre d'Italia: Nebbiolo autentico, rosa, ciliegia e tannino nobile — classe langarola a prezzo onesto." },
  { name: "Barbaresco Pio Cesare", regione: "Piemonte", description: "Barbaresco di scuola classica: elegante, speziato, di lunga persistenza — con tajarin al ragù e carni al vino." },
  { name: "Barbaresco Gaja", regione: "Piemonte", description: "La firma che ha portato il Barbaresco nel mondo: profondità, finezza e prestigio assoluto — un'icona per i grandi momenti." },
  { name: "Barbaresco Asili Michele Chiarlo", regione: "Piemonte", description: "Dal grande cru Asili: Nebbiolo aristocratico, floreale e setoso — eleganza pura per piatti al tartufo." },
  { name: "Barbaresco Bernardot Ceretto", regione: "Piemonte", description: "Cru di Treiso dal profilo teso e raffinato: frutto rosso, liquirizia e tannino fine — da carni brasate e formaggi DOP." },
  { name: "Barbaresco Montefico Riserva Produttori del Barbaresco", regione: "Piemonte", description: "Riserva di vigna storica: la potenza austera del Nebbiolo con anni di cantina alle spalle — per intenditori pazienti." },
  { name: "Barbaresco Reyna Michele Chiarlo", regione: "Piemonte", description: "Barbaresco armonico e accessibile, tra ciliegia, rosa e spezie dolci — introduce con grazia al mondo del Nebbiolo." },
  { name: "Barbarina Poderi Migliorini", regione: "Piemonte", description: "Rosso piemontese di piccola cantina, schietto e fruttato — la Langa di ogni giorno, senza pretese e senza delusioni." },
  { name: "Barbera d'Alba Ceretto", regione: "Piemonte", description: "Barbera d'Alba succosa e vibrante: ciliegia matura e acidità fresca — la compagna ideale di tajarin e agnolotti." },
  { name: "Barbera d'Alba Pio Cesare", regione: "Piemonte", description: "Barbera di stampo classico, piena e calorosa, con legno misurato — a tavola non sbaglia mai." },
  { name: "Barbera d'Alba Vignota Conterno Fantino", regione: "Piemonte", description: "Barbera di vigna in stile moderno: frutto lucido, morbidezza e slancio — golosa con carni e formaggi di media stagionatura." },
  { name: "Barbera d'Asti Bricco Bigotta Braida", regione: "Piemonte", description: "Barbera importante affinata in legno: concentrata, speziata, di lunga vita — dalla cantina che ha nobilitato la Barbera." },
  { name: "Barbera d'Asti Bricco Uccellone Braida", regione: "Piemonte", description: "La Barbera che ha fatto storia: opulenta, vellutata, con frutto profondo e legno nobile — bottiglia da grandi occasioni." },
  { name: "Barbera d'Asti La Court Michele Chiarlo", regione: "Piemonte", description: "Cru di Barbera elegante e moderno: mora, spezie e sorso pieno — con brasati e bagna caoda." },
  { name: "Barbera d'Asti Le Orme Michele Chiarlo", regione: "Piemonte", description: "Barbera quotidiana ben fatta: fragrante, succosa, dal sorso facile — il rosso da tavola piemontese per eccellenza." },
  { name: "Barbera d'Asti Mon Ross Forteto della Luja", regione: "Piemonte", description: "Barbera artigianale di collina: frutto vivo e freschezza contagiosa — da una piccola cantina di grande cuore." },
  { name: "Barbera del Monferrato La Monella Braida", regione: "Piemonte", description: "La Barbera vivace di Braida: brio, frutto croccante e allegria — nata per merende e salumi." },
  { name: "Barolo Pio Cesare", regione: "Piemonte", description: "Barolo classico e austero: rosa, catrame e liquirizia su tannino solenne — il re dei vini per bolliti e brasati." },
  { name: "Barolo Brunate Bricco Rocche Ceretto", regione: "Piemonte", description: "Dal cru Brunate: Barolo profondo e vellutato, di grande complessità — aristocrazia della Langa." },
  { name: "Barolo Cerequio Voerzio Roberto", regione: "Piemonte", description: "Barolo di culto da uno dei cru più ambiti: concentrazione, eleganza e rarità — per collezionisti e grandi ricorrenze." },
  { name: "Barolo Madonna Assunta Podere Rocche Manzoni", regione: "Piemonte", description: "Barolo generoso e moderno, dal frutto ricco e legno accarezzato — il carattere di Monforte in una bottiglia importante." },
  { name: "Barolo Prapò Bricco Rocche Ceretto", regione: "Piemonte", description: "Cru di Serralunga: struttura fitta, spezie ed energia minerale — un Barolo di lunga memoria." },
  { name: "Barolo Sorì Ginestra Conterno Fantino", regione: "Piemonte", description: "Dalla Ginestra di Monforte: Barolo profondo, balsamico, di trama finissima — il vertice della cantina." },
  { name: "Barolo Tortionano Michele Chiarlo", regione: "Piemonte", description: "Barolo dai suoli tortoniani: morbidezza, frutto rosso maturo e tannino gentile — classicità accessibile." },
  { name: "Barolo Zonchera Ceretto", regione: "Piemonte", description: "Il Barolo d'ingresso di Ceretto: fragrante, equilibrato, subito godibile — per innamorarsi del Nebbiolo senza aspettare decenni." },
  { name: "Dolcetto d'Alba Traversa", regione: "Piemonte", description: "Dolcetto genuino: frutto nero croccante, mandorla e beva quotidiana — il rosso feriale delle Langhe." },
  { name: "Dolcetto d'Alba Priavino Voerzio Roberto", regione: "Piemonte", description: "Dolcetto d'autore: succoso, pulito, dal frutto luminoso — la semplicità nelle mani di un grande produttore." },
  { name: "Dolcetto d'Alba Rossana Ceretto", regione: "Piemonte", description: "Dolcetto morbido e profumato dal vigneto Rossana — con paste al ragù e taglieri è sempre la risposta giusta." },
  { name: "Dolcetto d'Alba Savincato Tenuta L'Illuminata", regione: "Piemonte", description: "Dolcetto di La Morra fragrante e disinvolto, dal tipico finale ammandorlato — una beva compagnona per tutti i giorni." },
  { name: "Dolcetto di Dogliani Gillardi", regione: "Piemonte", description: "Dal territorio più vocato al Dolcetto: più struttura e profondità del solito — sorprende con primi ricchi e carni bianche." },
  { name: "Freisa Pio Cesare", regione: "Piemonte", description: "Autoctono ritrovato: Freisa fragrante di lampone e rosa, con vena vivace — una curiosità piemontese da salumi." },
  { name: "Grignolino Michele Chiarlo", regione: "Piemonte", description: "Grignolino scattante, dal colore chiaro e tannino pepato — leggero solo in apparenza, grande con fritture e antipasti." },
  { name: "Grignolino d'Asti Braida", regione: "Piemonte", description: "Il Grignolino secondo Braida: profumato, speziato, di beva golosa — anticonformista come chi lo sceglie." },
  { name: "Grignolino del Monferrato Pio Cesare", regione: "Piemonte", description: "Un gentiluomo di campagna: fine, secco, lievemente tannico — da provare con il vitello tonnato." },
  { name: "Il Bacialè Braida", regione: "Piemonte", description: "Blend giocoso di Barbera e vitigni internazionali: morbido, fruttato, conviviale — il vino che mette d'accordo tutta la tavola." },
  { name: "Langhe Rosso Monprà Conterno Fantino", regione: "Piemonte", description: "Nebbiolo, Barbera e Cabernet in equilibrio: struttura moderna e frutto ricco — un langarolo cosmopolita." },
  { name: "Le Grive Forteto della Luja", regione: "Piemonte", description: "Barbera e Pinot Nero in un blend originale: profumato, morbido, di personalità — accompagna salumi e primi piatti." },
  { name: "Nebbiolo Pio Cesare", regione: "Piemonte", description: "Nebbiolo Langhe di razza: rosa, ciliegia e tannino già armonico — l'anticamera nobile del Barolo." },
  { name: "Nebbiolo Produttori del Barbaresco", regione: "Piemonte", description: "Nebbiolo schietto dalla grande cooperativa: fragrante, teso, autentico — qualità langarola a prezzo gentile." },
  { name: "Nebbiolo Michele Chiarlo", regione: "Piemonte", description: "Nebbiolo immediato e curato: frutto rosso, viola e sorso elegante — per la cena piemontese di ogni settimana." },
  { name: "Nebbiolo d'Alba Ceretto", regione: "Piemonte", description: "Nebbiolo d'Alba fine e profumato, dal tannino levigato — con carni rosse e risotto al vino." },
  { name: "Nebbiolo Dancestro Tenuta L'Illuminata", regione: "Piemonte", description: "Nebbiolo di piccola tenuta a La Morra: floreale, sincero, ben fatto — piemontese nell'anima." },
  { name: "Nebbiolo Il Ciabot Traversa", regione: "Piemonte", description: "Nebbiolo rustico ed espressivo, dal cuore langarolo — da osteria, nel senso più bello del termine." },
  { name: "Pinot Nero Saracco", regione: "Piemonte", description: "Pinot Nero piemontese fine e fragrante, dal sorso fresco — inaspettato e riuscito, da provare con salumi crudi." },
  { name: "Sichivei Barbera d'Asti Bel Sit", regione: "Piemonte", description: "Barbera d'Asti di piccola cantina: franca, succosa, dal frutto pieno — la quotidianità fatta bene." },
  { name: "Gratticciaia Agricola Vallone", regione: "Puglia", description: "Negroamaro da uve appassite: ricco, caldo, tra confettura e spezie — l'Amarone del Salento, da formaggi e meditazione." },
  { name: "Primitivo Punta Aquila Tenute Rubino", regione: "Puglia", description: "Primitivo intenso e mediterraneo: prugna, ciliegia sotto spirito e sorso caldo — con grigliate e cucina saporita." },
  { name: "Primitivo Torcidoca Tormaresca", regione: "Puglia", description: "Primitivo polposo e speziato, dal tannino dolce — il Sud generoso di casa Antinori." },
  { name: "Spano Calò", regione: "Puglia", description: "Rosso salentino di tradizione, morbido e profondo, con frutto maturo — da carni al forno e formaggi stagionati." },
  { name: "Cannonau Pala", regione: "Sardegna", description: "Cannonau autentico: frutti rossi maturi, macchia mediterranea e calore isolano — con arrosti e pecorino è casa." },
  { name: "Siray Pala", regione: "Sardegna", description: "Syrah sardo speziato e scuro, dal sorso avvolgente — pepe e frutto per grigliate e piatti saporiti." },
  { name: "Turriga Argiolas", regione: "Sardegna", description: "L'icona rossa della Sardegna: Cannonau e uve isolane, potenza vellutata e complessità — una bottiglia da collezione." },
  { name: "Camelot Donnafugata", regione: "Sicilia", description: "Taglio bordolese maturato al sole di Sicilia: morbido, profondo, avvolgente — internazionale con cuore isolano." },
  { name: "Cerasuolo di Vittoria Planeta", regione: "Sicilia", description: "L'unica DOCG siciliana: Nero d'Avola e Frappato, ciliegia succosa e beva fresca — ottimo anche leggermente fresco." },
  { name: "Chiaramonte rosso Firriato", regione: "Sicilia", description: "Nero d'Avola fruttato e solare, dal sorso morbido — la Sicilia di ogni giorno nel bicchiere." },
  { name: "Faro Palari Palari", regione: "Sicilia", description: "Rarità dello Stretto da uve Nerello: eleganza quasi borgognona, spezie e mineralità — un mito per intenditori." },
  { name: "Harmonium Firriato", regione: "Sicilia", description: "Nero d'Avola in versione importante: concentrato, vellutato, con frutto nero e cacao — da carni importanti." },
  { name: "Hierà Hauner", regione: "Sicilia", description: "Rosso vulcanico delle Eolie: frutto scuro, erbe e salsedine — un'isola intera nel bicchiere." },
  { name: "Merlot Planeta", regione: "Sicilia", description: "Merlot mediterraneo: polposo, caldo, di grande morbidezza — coccola formaggi e secondi di carne." },
  { name: "Mille e una notte Donnafugata", regione: "Sicilia", description: "L'etichetta simbolo di Donnafugata: Nero d'Avola profondo, elegante, di lunga persistenza — una favola per le grandi occasioni." },
  { name: "Quater rosso Firriato", regione: "Sicilia", description: "Quattro autoctoni siciliani in blend: frutto ricco, spezie e carattere isolano — originale e conviviale." },
  { name: "Ribeca Firriato", regione: "Sicilia", description: "Perricone, antico vitigno siciliano: tannino fiero, frutto scuro e personalità — per chi ama le strade meno battute." },
  { name: "Rosso del Soprano Palari", regione: "Sicilia", description: "Fratello del Faro: Nerello fragrante, speziato, di beva raffinata — Messina d'autore." },
  { name: "Santa Cecilia Planeta", regione: "Sicilia", description: "Nero d'Avola di Noto elegante e profondo: more, carruba e spezie dolci — il sud-est della Sicilia al suo meglio." },
  { name: "Santagostino rosso Firriato", regione: "Sicilia", description: "Nero d'Avola e Syrah: frutto pieno, pepe e morbidezza solare — con arrosti e caciocavallo." },
  { name: "Tancredi Donnafugata", regione: "Sicilia", description: "Nero d'Avola e Cabernet dal fascino gattopardiano: frutto scuro, struttura ed eleganza — storico rosso da cene importanti." },
  { name: "Tripudium Rosso Pellegrino", regione: "Sicilia", description: "Rosso siciliano generoso e vellutato, dal frutto maturo — una festa per arrosti e formaggi saporiti." },
  { name: "Triskelè Planeta", regione: "Sicilia", description: "Blend siciliano armonioso tra autoctoni e internazionali: caldo, speziato, accogliente — il simbolo dell'isola già nel nome." },
  { name: "Borgeri Meletti Cavallari", regione: "Toscana", description: "Rosso di Bolgheri schietto e mediterraneo: frutto scuro, macchia e sorso pieno — il territorio bolgherese in versione quotidiana." },
  { name: "Brunello di Montalcino Castelgiocondo Marchesi dè Frescobaldi", regione: "Toscana", description: "Brunello di grande tenuta: Sangiovese profondo, tra amarena, cuoio e spezie — solidità aristocratica per gli arrosti." },
  { name: "Brunello di Montalcino Il Quercione Agricola San Felice", regione: "Toscana", description: "Brunello di selezione: frutto maturo, terra e tannino fitto — Montalcino in una bottiglia importante." },
  { name: "Brunello di Montalcino Madonna Piano Valdicava", regione: "Toscana", description: "Selezione celebre di Valdicava: opulenza, precisione e lunghissima vita — un Brunello da collezione." },
  { name: "Brunello di Montalcino Pian delle Bigne Antinori", regione: "Toscana", description: "Il Brunello di casa Antinori: elegante, armonico, dal frutto luminoso — un classico contemporaneo." },
  { name: "Brunello di Montalcino Poggio all'Oro Castello Banfi", regione: "Toscana", description: "La riserva di punta di Banfi: ricca, vellutata, con lunghi anni di affinamento — per le grandi celebrazioni." },
  { name: "Brunello di Montalcino Poggio alle Mura Castello Banfi", regione: "Toscana", description: "Il Brunello del castello: frutto profondo, spezie e trama levigata — moderno e maestoso." },
  { name: "Brunello di Montalcino Valdicava", regione: "Toscana", description: "Valdicava: Brunello di culto, materia ricca ed eleganza rigorosa — tra i più ricercati di Montalcino." },
  { name: "Brunello di Montalcino Mastroianni", regione: "Toscana", description: "Brunello di versante: teso, minerale, di grande classicità — per palati pazienti." },
  { name: "Brunello di Montalcino Siro Pacenti", regione: "Toscana", description: "Brunello di stile moderno: frutto lucido, legno raffinato e morbidezza — Montalcino contemporaneo." },
  { name: "Brunello di Montalcino Agricola San Felice", regione: "Toscana", description: "Brunello equilibrato e sincero: amarena, viola e tannino elegante — l'essenza del Sangiovese Grosso." },
  { name: "Brunello di Montalcino San Giorgio", regione: "Toscana", description: "Brunello dal carattere schietto: terra, frutto e sapore — Montalcino senza fronzoli." },
  { name: "Brunello di Montalcino Col d'Orcia", regione: "Toscana", description: "Dalla storica tenuta biologica: Brunello classico, austero il giusto, di lunga persistenza — vero Sangiovese." },
  { name: "Brunello di Montalcino Fanti", regione: "Toscana", description: "Brunello generoso di Castelnuovo dell'Abate: frutto caldo e trama vellutata — accogliente e profondo." },
  { name: "Brunello di Montalcino Castello Banfi", regione: "Toscana", description: "Il Brunello che ha aperto Montalcino al mondo: pieno, moderno, affidabile — sempre una certezza." },
  { name: "Brunello di Montalcino Biondi e Santi", regione: "Toscana", description: "La leggenda: qui è nato il Brunello. Austero, longevo, monumentale — una pagina di storia italiana nel calice." },
  { name: "Brunello di Montalcino Riserva Col d'Orcia", regione: "Toscana", description: "Riserva severa e nobile, fatta per lunghi invecchiamenti: spezie, cuoio e frutto asciutto — patrimonio da cantina." },
  { name: "Cacciacone San Giorgio", regione: "Toscana", description: "Rosso toscano di tenuta: Sangiovese schietto, fruttato, di beva franca — la Toscana quotidiana." },
  { name: "Casalferro Barone Ricasoli", regione: "Toscana", description: "Merlot in purezza dal Chianti storico: morbido, profondo, moderno — il lato internazionale del Barone." },
  { name: "Cepparello Isole Olena", regione: "Toscana", description: "Sangiovese in purezza divenuto mito: eleganza, energia e profondità — tra i più grandi rossi toscani." },
  { name: "Chianti Classico Castello Brolio Barone Ricasoli", regione: "Toscana", description: "Dal castello dove nacque la formula del Chianti: selezione importante, frutto nobile e spezie — storia viva." },
  { name: "Chianti Classico Castello Fonterutoli Mazzei", regione: "Toscana", description: "Chianti Classico di punta dei Mazzei: fitto, elegante, di lunga persistenza — sei secoli di famiglia nel bicchiere." },
  { name: "Chianti Classico Querciabella Agricola Querciabella", regione: "Toscana", description: "Chianti Classico in biodinamica: purezza di frutto, finezza e slancio — gallo nero d'autore." },
  { name: "Chianti Classico Riserva Agricola San Felice", regione: "Toscana", description: "Riserva armoniosa: ciliegia matura, spezie e tannino levigato — il Chianti della domenica." },
  { name: "Chianti Classico Riserva Rancia Felsina", regione: "Toscana", description: "Cru leggendario da vigna Rancia: austero, minerale, longevo — Sangiovese di rango." },
  { name: "Chianti Classico Rocca Guicciarda Barone Ricasoli", regione: "Toscana", description: "Riserva accogliente e speziata, dal frutto caldo — gallo nero affidabile per arrosti e pici al ragù." },
  { name: "Chianti Classico Isole Olena", regione: "Toscana", description: "Chianti Classico luminoso e succoso, di beva elegante — la mano di un maestro del Sangiovese." },
  { name: "Chianti Classico Felsina", regione: "Toscana", description: "Chianti Classico di Castelnuovo Berardenga: terroso, sincero, di carattere — con la bistecca è un matrimonio." },
  { name: "Chianti Classico Brolio Barone Ricasoli", regione: "Toscana", description: "Il gallo nero del Barone: fragrante, equilibrato, immediato — un classico della tavola toscana." },
  { name: "Chianti Classico Fonterutoli Mazzei", regione: "Toscana", description: "Chianti Classico vivo e moderno: ciliegia croccante e spezie fini — la firma Mazzei di ogni giorno." },
  { name: "Chianti Classico Peppoli Antinori", regione: "Toscana", description: "Chianti Classico morbido e fruttato, subito piacevole — il volto gentile del gallo nero." },
  { name: "Chianti Classico Poggio ai Frati Rocca di Castagnoli", regione: "Toscana", description: "Riserva di stampo tradizionale: ciliegia sotto spirito, cuoio e tannino asciutto — chiantigiano verace." },
  { name: "Chianti Rufina Marchesi dè Frescobaldi", regione: "Toscana", description: "Chianti di Rufina fresco ed elegante, di alta collina — con salumi toscani e pappardelle." },
  { name: "Cortaccio Villa Cafaggio", regione: "Toscana", description: "Cabernet in purezza dal cuore del Chianti: struttura, frutto scuro ed eleganza internazionale — da carni rosse." },
  { name: "Excelsus Castello Banfi", regione: "Toscana", description: "Cabernet e Merlot di Montalcino: opulento, vellutato, cosmopolita — il volto bordolese di Banfi." },
  { name: "Fontalloro Felsina", regione: "Toscana", description: "Sangiovese in purezza tra Chianti e crete senesi: profondo, luminoso, di grande futuro — un fuoriclasse." },
  { name: "Guado al Tasso Antinori", regione: "Toscana", description: "Bolgheri Superiore di casa Antinori: taglio bordolese di grande respiro — eleganza marittima e prestigio." },
  { name: "Guidalberto Tenuta San Guido", regione: "Toscana", description: "Il secondo vino della tenuta del Sassicaia: Cabernet e Merlot già armonici, eleganti — la porta d'ingresso alla leggenda." },
  { name: "Le Difese Tenuta San Guido", regione: "Toscana", description: "Cabernet e Sangiovese dalla tenuta del Sassicaia: fragrante, succoso, immediato — nobiltà accessibile." },
  { name: "Le Serre Nuove Ornellaia", regione: "Toscana", description: "Il secondo vino di Ornellaia: ricco, avvolgente, bordolese nell'anima — grande stile da subito." },
  { name: "Le Volte Ornellaia", regione: "Toscana", description: "L'ingresso nel mondo Ornellaia: morbido, mediterraneo, ben ritmato — eleganza quotidiana." },
  { name: "Morellino di Scansano Poggio Valente Fattorie le Pupille", regione: "Toscana", description: "Cru di Morellino: Sangiovese maremmano profondo e succoso — il mare dentro un rosso di razza." },
  { name: "Morellino di Scansano Bronzone Mazzei", regione: "Toscana", description: "Morellino di tenuta: caldo, fruttato, dal tannino gentile — la Maremma golosa." },
  { name: "Morellino di Scansano Biondi e Santi", regione: "Toscana", description: "Morellino firmato da un nome storico: frutto vivo e sorso elegante — Sangiovese di mare." },
  { name: "Morellino di Scansano Val delle Rose", regione: "Toscana", description: "Morellino fragrante e immediato: ciliegia, macchia e beva facile — con i salumi di cinta senese è perfetto." },
  { name: "Morellino di Scansano Fattoria Le Pupille", regione: "Toscana", description: "Il Morellino di riferimento: succoso, schietto, sempre in forma — l'allegria della Maremma." },
  { name: "Morellino di Scansano 414 Podere 414", regione: "Toscana", description: "Morellino artigianale del podere 414: materia, freschezza e carattere — maremmano doc." },
  { name: "Morellino di Scansano Capatosta Poggio Argentiera", regione: "Toscana", description: "Morellino di vecchie vigne, testardo di nome e generoso di fatto — frutto pieno e sapore." },
  { name: "Morellino di Scansano Riserva Val delle Rose", regione: "Toscana", description: "Riserva maremmana: più struttura, spezie e legno ben dosato — il Morellino vestito a festa." },
  { name: "Morellino di Scansano Santa Maria Marchesi dè Frescobaldi", regione: "Toscana", description: "Morellino luminoso e morbido, di frutto rosso maturo — la Maremma secondo Frescobaldi." },
  { name: "Nobile Montepulciano La Braccesca", regione: "Toscana", description: "Vino Nobile elegante: Sangiovese di Montepulciano con frutto scuro e spezie — nobiltà autentica a tavola." },
  { name: "Poggio alla Badiola Mazzei", regione: "Toscana", description: "Toscana IGT fragrante e conviviale, Sangiovese con un tocco di Merlot — la scorciatoia intelligente per il buon bere." },
  { name: "Pomino Rosso Marchesi dè Frescobaldi", regione: "Toscana", description: "Pinot Nero e Sangiovese d'alta collina: fine, boschivo, raro — una piccola Borgogna toscana." },
  { name: "Rosso di Montalcino Siro Pacenti", regione: "Toscana", description: "Rosso di Montalcino moderno e lucido: il fratello giovane del Brunello, subito godibile." },
  { name: "Rosso di Montalcino Castello Banfi", regione: "Toscana", description: "Sangiovese di Montalcino fragrante e rotondo — l'anteprima accessibile del Brunello di casa." },
  { name: "Rosso di Montalcino Biondi e Santi", regione: "Toscana", description: "Il Rosso della tenuta più storica di Montalcino: austero, puro, di scuola — il Brunello in gioventù." },
  { name: "Rosso di Montalcino Mastroianni", regione: "Toscana", description: "Rosso teso e minerale, di scuola classica — piccolo solo di nome." },
  { name: "Rosso di Montalcino Campogiovanni Agricola San Felice", regione: "Toscana", description: "Rosso di Montalcino solare e armonico — la quotidianità del Sangiovese Grosso." },
  { name: "Rosso di Montalcino Ciampoleto San Giorgio", regione: "Toscana", description: "Rosso schietto di Montalcino, fruttato e diretto — trattoria d'eccellenza." },
  { name: "Ruit Hora Caccia al Piano", regione: "Toscana", description: "Bolgheri DOC dal frutto ricco e dalla morbidezza mediterranea — bordolese di costa, elegante e godibile." },
  { name: "Sassicaia Tenuta San Guido", regione: "Toscana", description: "Il vino italiano più celebre al mondo: Cabernet di Bolgheri, eleganza assoluta e mito — non ha bisogno di presentazioni." },
  { name: "Sassicaia Tenuta San Guido", regione: "Toscana", description: "Il vino italiano più celebre al mondo: Cabernet di Bolgheri, eleganza assoluta e mito — non ha bisogno di presentazioni." },
  { name: "Sassoalloro Biondi e Santi", regione: "Toscana", description: "Sangiovese moderno e succoso firmato Biondi Santi: frutto pieno, morbidezza e classe — quotidiano di lusso." },
  { name: "Serrata Belguardo Mazzei", regione: "Toscana", description: "Rosso maremmano fragrante, con frutto vivo e spezie leggere — mediterraneo e disinvolto." },
  { name: "Solaia Antinori", regione: "Toscana", description: "Cabernet e Sangiovese da un solo vigneto assolato: potenza, eleganza e fama mondiale — un monumento del vino italiano." },
  { name: "Summus Castello Banfi", regione: "Toscana", description: "Sangiovese, Cabernet e Syrah in armonia: ricco, speziato, internazionale — la sintesi moderna di Montalcino." },
  { name: "Tignanello Antinori", regione: "Toscana", description: "Il supertuscan che ha cambiato la storia: Sangiovese e Cabernet, eleganza fiorentina e profondità — sempre desiderato." },
  { name: "Brentino Maculan", regione: "Trentino", description: "Merlot e Cabernet di Breganze: morbido, fruttato, di beva generosa — il rosso quotidiano di casa Maculan." },
  { name: "Cabernet Maculan", regione: "Trentino", description: "Cabernet dal profilo pulito: frutto nero, lieve nota erbacea e sorso armonico — con carni e formaggi." },
  { name: "Granato Foradori", regione: "Trentino", description: "Teroldego in purezza divenuto icona: profondo, minerale, biodinamico — un grande rosso alpino." },
  { name: "Marzemino Bossi Fedrigotti", regione: "Trentino", description: "Il Marzemino celebrato nel Don Giovanni di Mozart: fragrante, fruttato, di beva gentile — tradizione trentina." },
  { name: "Teroldego Foradori", regione: "Trentino", description: "Teroldego rotaliano vivo e succoso: mora, viola ed energia — la firma di Elisabetta Foradori." },
  { name: "Teroldego Bossi Fedrigotti", regione: "Trentino", description: "Teroldego classico: colore fitto, frutti neri e tannino morbido — con polenta e carni salate." },
  { name: "Campoleone Lamborghini", regione: "Umbria", description: "Sangiovese e Merlot umbri in versione potente: frutto denso e legno elegante — un fuoriserie, come da cognome." },
  { name: "Pinot Nero Antinori", regione: "Umbria", description: "Pinot Nero della Sala: fine, fragrante, con frutto rosso e sottobosco — eleganza borgognona in Umbria." },
  { name: "Rosso Conero Serrano Umani Ronchi", regione: "Umbria", description: "Montepulciano del Conero: frutto scuro, macchia e sorso robusto — verace e generoso." },
  { name: "Rosso di Montefalco Tenuta Alzatura", regione: "Umbria", description: "Sangiovese e Sagrantino in equilibrio: caldo, speziato, accogliente — l'Umbria a tavola." },
  { name: "Sagrantino di Montefalco Caprai", regione: "Umbria", description: "Il Sagrantino che ha conquistato il mondo: tannino monumentale, frutto scuro e lunga vita — da brasati e grandi formaggi." },
  { name: "Sagrantino di Montefalco Adanti", regione: "Umbria", description: "Sagrantino di scuola tradizionale: austero, profondo, sincero — Montefalco d'altri tempi." },
  { name: "Sagrantino di Montefalco Tenuta Alzatura", regione: "Umbria", description: "Sagrantino intenso e vellutato, tra mora, spezie e cacao — potenza umbra ben educata." },
  { name: "San Giorgio Lungarotti", regione: "Umbria", description: "Storico blend umbro di Sangiovese e Cabernet: complesso, maturo, di lunga tradizione — Torgiano nel calice." },
  { name: "Fumin Vigne la Tour Les Cretes", regione: "Valle d'Aosta", description: "Autoctono valdostano di montagna: speziato, scuro, dal tannino vivo — carattere alpino con carni e fontina." },
  { name: "Pinot Nero Les Cretes", regione: "Valle d'Aosta", description: "Pinot Nero d'alta quota: fragrante, teso, con frutti rossi croccanti — freschezza di montagna." },
  { name: "Rouge de Vigne Les Cretes", regione: "Valle d'Aosta", description: "Blend rosso valdostano agile e profumato — il quotidiano delle Alpi, da merende e taglieri." },
  { name: "Amarone Valpolicella Valpantena Bertani", regione: "Veneto", description: "Amarone della Valpantena: appassimento più snello, frutto elegante e spezie — Bertani in versione contemporanea." },
  { name: "Amarone Cl. Serego Alighieri Masi", regione: "Veneto", description: "Dall'antica tenuta della famiglia di Dante: Amarone nobile, vellutato, con ciliegia matura e spezie — seicento anni di storia." },
  { name: "Amarone Cl. Valpolicella Allegrini", regione: "Veneto", description: "Amarone moderno e magnetico: frutto lussureggiante, morbidezza e potenza misurata — tra i più amati." },
  { name: "Amarone Cl. Valpolicella Costasera Masi", regione: "Veneto", description: "Il classico che guarda il lago: ricco, avvolgente, con frutta appassita e cacao — l'Amarone per antonomasia." },
  { name: "Amarone Classico Valpolicella Dal Forno", regione: "Veneto", description: "Culto assoluto: concentrazione monumentale, precisione e profondità — uno dei rossi più ricercati d'Italia." },
  { name: "Amarone Classico Valpolicella Bertani", regione: "Veneto", description: "L'Amarone della tradizione: austero, speziato, di longevità proverbiale — invecchia per decenni con grazia." },
  { name: "Amarone Classico Valpolicella Zenato", regione: "Veneto", description: "Amarone generoso e vellutato: amarena, prugna e spezie dolci — un abbraccio veronese per l'inverno." },
  { name: "Amarone Classico Valpolicella Speri", regione: "Veneto", description: "Amarone di famiglia, artigianale e classico: frutto profondo e mano tradizionale — Valpolicella autentica." },
  { name: "Amarone Classico Valpolicella Bertani", regione: "Veneto", description: "L'Amarone della tradizione: austero, speziato, di longevità proverbiale — invecchia per decenni con grazia." },
  { name: "Amarone Classico Valpolicella Bertani", regione: "Veneto", description: "L'Amarone della tradizione: austero, speziato, di longevità proverbiale — invecchia per decenni con grazia." },
  { name: "Amarone della Valpolicella Cecilia Beretta", regione: "Veneto", description: "Amarone armonioso e accessibile: frutta sotto spirito, cioccolato e rotondità — per iniziare ad amarlo." },
  { name: "Bardolino Le Fraghe", regione: "Veneto", description: "Bardolino fresco e succoso: ciliegia croccante e beva gioiosa — provalo fresco con pizza e pesce di lago." },
  { name: "Brolo di Campofiorin Masi", regione: "Veneto", description: "Ripasso evoluto e ricco, da uve selezionate: frutto denso e spezie — a metà strada tra Campofiorin e Amarone." },
  { name: "Fojaneghe Bossi Fedrigotti", regione: "Veneto", description: "Storico taglio bordolese, tra i primi in Italia: elegante e maturo — una pagina di storia enologica." },
  { name: "Marzemino Costaripa", regione: "Veneto", description: "Marzemino gardesano fragrante e gentile: frutto rosso e mandorla — con primi e salumi leggeri." },
  { name: "Ripassa Zenato", regione: "Veneto", description: "Il Ripasso più famoso: pieno, vellutato, con ciliegia matura e spezie — la via di mezzo perfetta verso l'Amarone." },
  { name: "Ripasso Campofiorin Masi", regione: "Veneto", description: "Il capostipite della tecnica del ripasso: corpo, morbidezza e frutto generoso — un classico intramontabile." },
  { name: "Secco Bertani Vintage Bertani", regione: "Veneto", description: "Rosso veronese in stile ottocentesco: speziato, asciutto, di grande fascino retrò — con risotto all'amarone." },
];

const run = async () => {
  await mongoose.connect(process.env.MONGODB_URI);

  const existing = await Wine.countDocuments({ category: "rossi" });
  if (existing > 0) {
    console.error(`Esistono già ${existing} vini rossi nel database — importazione annullata per evitare duplicati.`);
    await mongoose.disconnect();
    process.exit(1);
  }

  const docs = ROSSI.map((w) => ({ ...w, category: "rossi" }));
  const inserted = await Wine.insertMany(docs);
  console.log(`Importati ${inserted.length} vini rossi.`);

  await mongoose.disconnect();
};

run();
